# Group BY:- it is used to join two or more column and give me result.

In [2]:
import pandas as pd

data = {
    "Patient_ID": [101,102,103,104,105,106,107,108,109,110],
    "Age": [25,45,35,60,50,28,65,40,55,30],
    "Gender": ["Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female"],
    "Department": ["Cardiology","Neurology","Cardiology","Orthopedic",
                   "Neurology","Cardiology","Orthopedic","Neurology",
                   "Cardiology","Orthopedic"],
    "City": ["Nagpur","Pune","Nagpur","Mumbai","Pune",
             "Nagpur","Mumbai","Pune","Nagpur","Mumbai"],
    "Treatment_Cost": [50000,35000,60000,45000,30000,
                       55000,70000,40000,65000,50000],
    "Hospital_Stay": [5,3,6,4,2,5,7,3,6,4]
}

df = pd.DataFrame(data)

df

   Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0         101   25    Male  Cardiology  Nagpur           50000              5
1         102   45  Female   Neurology    Pune           35000              3
2         103   35    Male  Cardiology  Nagpur           60000              6
3         104   60  Female  Orthopedic  Mumbai           45000              4
4         105   50    Male   Neurology    Pune           30000              2
5         106   28  Female  Cardiology  Nagpur           55000              5
6         107   65    Male  Orthopedic  Mumbai           70000              7
7         108   40  Female   Neurology    Pune           40000              3
8         109   55    Male  Cardiology  Nagpur           65000              6
9         110   30  Female  Orthopedic  Mumbai           50000              4

1. हर city में कितने patients हैं?

In [3]:
df.groupby("City")["Patient_ID"].count()

City
Mumbai    3
Nagpur    4
Pune      3
Name: Patient_ID, dtype: int64

2. हर city की average age क्या है?

In [4]:
df.groupby("City")["Age"].mean()

City
Mumbai    51.666667
Nagpur    35.750000
Pune      45.000000
Name: Age, dtype: float64

1. Average treatment cost for each department.

In [8]:
df.groupby("Department")["Treatment_Cost"].mean()

Department
Cardiology    57500.0
Neurology     35000.0
Orthopedic    55000.0
Name: Treatment_Cost, dtype: float64

Q2. Total treatment cost for each department.

In [9]:
df.groupby("Department")["Treatment_Cost"].sum()

Department
Cardiology    230000
Neurology     105000
Orthopedic    165000
Name: Treatment_Cost, dtype: int64

Q3. Number of patients in each department.

In [10]:
df.groupby("Department")["Patient_ID"].count()

Department
Cardiology    4
Neurology     3
Orthopedic    3
Name: Patient_ID, dtype: int64

Q4. Average hospital stay for each department.

In [11]:
df.groupby("Department")["Hospital_Stay"].mean()

Department
Cardiology    5.500000
Neurology     2.666667
Orthopedic    5.000000
Name: Hospital_Stay, dtype: float64

Q5. Total treatment cost for each city.

In [12]:
df.groupby("City")["Treatment_Cost"].sum()

City
Mumbai    165000
Nagpur    230000
Pune      105000
Name: Treatment_Cost, dtype: int64

Q6. Compare average treatment cost of Male and Female patients.

In [13]:
df.groupby("Gender")["Treatment_Cost"].mean()

Gender
Female    45000.0
Male      55000.0
Name: Treatment_Cost, dtype: float64

Q7. Number of patients from each city.

In [14]:
df.groupby("City")["Patient_ID"].count()

City
Mumbai    3
Nagpur    4
Pune      3
Name: Patient_ID, dtype: int64

Q8. Average treatment cost for each City + Department combination.

In [16]:
df.groupby(["Department","City"])["Treatment_Cost"].mean()

Department  City
Cardiology  Nagpur    57500.0
Neurology   Pune      35000.0
Orthopedic  Mumbai    55000.0
Name: Treatment_Cost, dtype: float64

Q9. Write code for department-wise average Hospital_Stay.

In [17]:
df.groupby("Department")["Hospital_Stay"].mean()

Department
Cardiology    5.500000
Neurology     2.666667
Orthopedic    5.000000
Name: Hospital_Stay, dtype: float64

Q10. Write code for department-wise highest Treatment_Cost.

In [18]:
df.groupby("Department")["Treatment_Cost"].max()

Department
Cardiology    65000
Neurology     40000
Orthopedic    70000
Name: Treatment_Cost, dtype: int64

Q11. Write code for department-wise total Treatment_Cost.

In [19]:
df.groupby("Department")["Treatment_Cost"].sum()

Department
Cardiology    230000
Neurology     105000
Orthopedic    165000
Name: Treatment_Cost, dtype: int64

Q12. Write code for department-wise patient count.

In [20]:
df.groupby("Department")["Patient_ID"].count()

Department
Cardiology    4
Neurology     3
Orthopedic    3
Name: Patient_ID, dtype: int64

In [ ]:
Q13. The hospital manager wants one report containing, for every department: average treatment cost,
total treatment cost, minimum treatment cost and maximum treatment cost. First identify the Group By
column, Analysis column and functions, then write the code.

In [30]:
df.groupby(["Department"])["Treatment_Cost"].agg(["mean","sum","max","min"])

               mean     sum    max    min
Department
Cardiology  57500.0  230000  65000  50000
Neurology   35000.0  105000  40000  30000
Orthopedic  55000.0  165000  70000  45000

Q14. Find the average Hospital_Stay for each department and arrange the result from highest to lowest.
Decide which department has the highest average stay.

In [55]:
df.groupby("Department")["Hospital_Stay"].mean().sort_values(ascending=False)

Department
Cardiology    5.500000
Orthopedic    5.000000
Neurology     2.666667
Name: Hospital_Stay, dtype: float64