# interpolation:- interpolation is define as the find of missing numeric value based on surrounding value.

In [7]:
import pandas as pd

data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105", "P106", "P107", "P108", "P109", "P110"],
    
    "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],
    
    "City": [
        "Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
        "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
        "Hyderabad", "Karimnagar"
    ],
    
    "Surgery_Type": [
        "Cholecystectomy", "CABG", "Appendectomy", "Hernia Repair",
        "Knee Replacement", "PTCA", "Appendectomy",
        "Cholecystectomy", "Hernia Repair", "Knee Replacement"
    ],
    
    "Operation_Duration_Min": [
        90, 240, None, 110, 180, None, 70, 95, 120, 200
    ],
    
    "Length_of_Stay_Days": [
        2, 7, 1, None, 5, 4, None, 2, 3, 6
    ],
    
    "Admission_Type": [
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Emergency", "Emergency",
        "Planned", "Planned", "Planned"
    ]
}

df = pd.DataFrame(data)

df

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90.0,2.0,Planned
1,P102,62,Warangal,CABG,240.0,7.0,Emergency
2,P103,34,Hyderabad,Appendectomy,NaN,1.0,Emergency
3,P104,55,Vijayawada,Hernia Repair,110.0,NaN,Planned
4,P105,41,Hyderabad,Knee Replacement,180.0,5.0,Planned
5,P106,68,Nizamabad,PTCA,NaN,4.0,Emergency
6,P107,29,Hyderabad,Appendectomy,70.0,NaN,Emergency
7,P108,52,Warangal,Cholecystectomy,95.0,2.0,Planned
8,P109,47,Hyderabad,Hernia Repair,120.0,3.0,Planned
9,P110,73,Karimnagar,Knee Replacement,200.0,6.0,Planned

In [9]:
df["Length_of_Stay_Days"]=df["Length_of_Stay_Days"].interpolate()
df["Length_of_Stay_Days"]

0    2.0
1    7.0
2    1.0
3    3.0
4    5.0
5    4.0
6    3.0
7    2.0
8    3.0
9    6.0
Name: Length_of_Stay_Days, dtype: float64

In [11]:
df[["Patient_ID","Length_of_Stay_Days"]]

  Patient_ID  Length_of_Stay_Days
0       P101                  2.0
1       P102                  7.0
2       P103                  1.0
3       P104                  3.0
4       P105                  5.0
5       P106                  4.0
6       P107                  3.0
7       P108                  2.0
8       P109                  3.0
9       P110                  6.0