Python Logic WarmUp

In [49]:
import pandas as pd
Age={"Age":[25, 45, 62, 34, 55, 41, 68, 29, 52, 47]}
df=pd.DataFrame(Age)
df

   Age
0   25
1   45
2   62
3   34
4   55
5   41
6   68
7   29
8   52
9   47

23. Print the first element.

In [50]:
df.head(1)

   Age
0   25

24. Print the last element.

In [51]:
df.tail(1)

   Age
9   47


25. Find the length.

In [52]:
df.__len__()

10

26. Find the maximum age.

In [53]:
df.max()

Age    68
dtype: int64

27. Find the minimum age.

In [54]:
df.min()

Age    25
dtype: int64


28. Find ages greater than 50.

In [57]:
df[df["Age"]>50],"Age"

(   Age
 2   62
 4   55
 6   68
 8   52,
 'Age')

29. Find ages less than 40.

In [58]:
df[df["Age"]<40],"Age"

(   Age
 0   25
 3   34
 7   29,
 'Age')

30. Count ages greater than 50.

In [59]:
df[df["Age"]>50].count()

Age    4
dtype: int64

31. Calculate average age.

In [60]:
df.mean()

Age    45.8
dtype: float64


32. Check whether 55 exists.

In [61]:
df[df["Age"]==55]

   Age
4   55

33. Find the position of 55.

In [67]:
df[df['Age'] == 55].index

RangeIndex(start=4, stop=5, step=1)

34. Find the second largest age.

In [69]:
df["Age"].nlargest(2).iloc[-1]

np.int64(62)

35. Find the second smallest age.

In [71]:
df["Age"].nsmallest(2).iloc[-1]

np.int64(29)