In [1]:
import pandas as pd

data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110"],

    "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],

    "City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
             "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
             "Hyderabad", "Karimnagar"],

    "Surgery_Type": [
        "Cholecystectomy", "CABG", "Appendectomy",
        "Hernia Repair", "Knee Replacement", "PTCA",
        "Appendectomy", "Cholecystectomy",
        "Hernia Repair", "Knee Replacement"
    ],

    "Operation_Duration_Min": [90, 240, 75, 110, 180,
                               150, 70, 95, 120, 200],

    "Length_of_Stay_Days": [2, 7, 1, 3, 5,
                            4, 1, 2, 3, 6],

    "Admission_Type": [
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Planned"
    ]
}

df = pd.DataFrame(data)

df

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned


37. Display the first 5 rows.

In [2]:
df.head(5)

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned


38. Display the last 5 rows.

In [3]:
df.tail(5)

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned


39. Check shape.

In [4]:
df.shape

(10, 7)


40. Check columns.

In [5]:
df.columns

Index(['Patient_ID', 'Age', 'City', 'Surgery_Type', 'Operation_Duration_Min',
       'Length_of_Stay_Days', 'Admission_Type'],
      dtype='str')

41. Check dtypes.

In [6]:
df.dtypes

Patient_ID                  str
Age                       int64
City                        str
Surgery_Type                str
Operation_Duration_Min    int64
Length_of_Stay_Days       int64
Admission_Type              str
dtype: object


42. Display only Patient_ID.

In [10]:
df[:][["Patient_ID"]]

  Patient_ID
0       P101
1       P102
2       P103
3       P104
4       P105
5       P106
6       P107
7       P108
8       P109
9       P110


43. Display Patient_ID and Age

In [11]:
df[:][["Patient_ID","Age"]]

  Patient_ID  Age
0       P101   45
1       P102   62
2       P103   34
3       P104   55
4       P105   41
5       P106   68
6       P107   29
7       P108   52
8       P109   47
9       P110   73

44. Display Patient_ID, City and Surgery_Type.

In [12]:
df[:][["Patient_ID","City","Surgery_Type"]]

  Patient_ID        City      Surgery_Type
0       P101   Hyderabad   Cholecystectomy
1       P102    Warangal              CABG
2       P103   Hyderabad      Appendectomy
3       P104  Vijayawada     Hernia Repair
4       P105   Hyderabad  Knee Replacement
5       P106   Nizamabad              PTCA
6       P107   Hyderabad      Appendectomy
7       P108    Warangal   Cholecystectomy
8       P109   Hyderabad     Hernia Repair
9       P110  Karimnagar  Knee Replacement


45. Display Surgery_Type and Operation_Duration_Min.

In [13]:
df[:][["Surgery_Type","Operation_Duration_Min"]]

       Surgery_Type  Operation_Duration_Min
0   Cholecystectomy                      90
1              CABG                     240
2      Appendectomy                      75
3     Hernia Repair                     110
4  Knee Replacement                     180
5              PTCA                     150
6      Appendectomy                      70
7   Cholecystectomy                      95
8     Hernia Repair                     120
9  Knee Replacement                     200

46. Find patients from Hyderabad.

In [15]:
df[df["City"]=="Hyderabad"]["Patient_ID"]

0    P101
2    P103
4    P105
6    P107
8    P109
Name: Patient_ID, dtype: str

47. Find Emergency patients.

In [16]:
df[df["Admission_Type"]=="Emergency"]["Patient_ID"]

1    P102
2    P103
5    P106
6    P107
Name: Patient_ID, dtype: str


48. Find Planned patients.

In [18]:
df[df["Admission_Type"]=="Planned"]["Patient_ID"]

0    P101
3    P104
4    P105
7    P108
8    P109
9    P110
Name: Patient_ID, dtype: str

49. Find patients with Age > 50.

In [19]:
df[df["Age"]>50]["Patient_ID"]

1    P102
3    P104
5    P106
7    P108
9    P110
Name: Patient_ID, dtype: str


50. Find patients with Age < 40.

In [20]:
df[df["Age"]<40]["Patient_ID"]

2    P103
6    P107
Name: Patient_ID, dtype: str

51. Find patients with Operation_Duration_Min > 150.

In [21]:
df[df["Operation_Duration_Min"]>150]["Patient_ID"]

1    P102
4    P105
9    P110
Name: Patient_ID, dtype: str


52. Find patients with Length_of_Stay_Days > 3.

In [23]:
df[df["Operation_Duration_Min"]>3]["Patient_ID"]

0    P101
1    P102
2    P103
3    P104
4    P105
5    P106
6    P107
7    P108
8    P109
9    P110
Name: Patient_ID, dtype: str


53. Find patients from Hyderabad AND Emergency.

In [25]:
df[(df["City"]=="Hyderabad")&(df["Admission_Type"]=="Emergency")]["Patient_ID"]

2    P103
6    P107
Name: Patient_ID, dtype: str


54. Find patients from Hyderabad OR Warangal.

In [26]:
df[(df["City"]=="Hyderabad")|(df["City"]=="Warangal")]["Patient_ID"]

0    P101
1    P102
2    P103
4    P105
6    P107
7    P108
8    P109
Name: Patient_ID, dtype: str

55. Find patients with:

Age > 50

AND

Operation_Duration_Min > 100

In [27]:
df[(df["Age"]>50)&(df["Operation_Duration_Min"]>100)]["Patient_ID"]

1    P102
3    P104
5    P106
9    P110
Name: Patient_ID, dtype: str

  
56. Find patients with:

Age > 50

OR

Length_of_Stay_Days > 4

In [31]:
df[(df["Age"]>50)|(df["Length_of_Stay_Days"])]["Patient_ID"]

0    P101
1    P102
2    P103
3    P104
4    P105
5    P106
6    P107
7    P108
8    P109
9    P110
Name: Patient_ID, dtype: str


57. Sort by Operation_Duration_Min from highest to lowest.

In [40]:
df.sort_values(by='Operation_Duration_Min', ascending=False)

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
1,P102,62,Warangal,CABG,240,7,Emergency
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
5,P106,68,Nizamabad,PTCA,150,4,Emergency
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency

58. Sort by Age from lowest to highest.

In [41]:
df.sort_values(by='Age', ascending=True)

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
5,P106,68,Nizamabad,PTCA,150,4,Emergency
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

59. Sort by Length_of_Stay_Days from highest to lowest.

In [42]:
df.sort_values(by="Length_of_Stay_Days" , ascending=False)

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
1,P102,62,Warangal,CABG,240,7,Emergency
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
5,P106,68,Nizamabad,PTCA,150,4,Emergency
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency

60. Display only the top 3 patients based on operation duration.

In [49]:
[df["Operation_Duration_Min"].head(3)]

[0     90
 1    240
 2     75
 Name: Operation_Duration_Min, dtype: int64]


61. Find average Age.

In [50]:
df["Age"].mean()

np.float64(50.6)


62. Find average Operation_Duration_Min.

In [51]:
df["Operation_Duration_Min"].mean()

np.float64(133.0)

63. Find average Length_of_Stay_Days.

In [52]:
df["Length_of_Stay_Days"].mean()

np.float64(3.4)