DAY 3 – ADVANCED LOGIC PRACTICE

In [2]:
import pandas as pd

data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110"],

    "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],

    "City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
             "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
             "Hyderabad", "Karimnagar"],

    "Surgery_Type": [
        "Cholecystectomy", "CABG", "Appendectomy",
        "Hernia Repair", "Knee Replacement", "PTCA",
        "Appendectomy", "Cholecystectomy",
        "Hernia Repair", "Knee Replacement"
    ],

    "Operation_Duration_Min": [90, 240, 75, 110, 180,
                               150, 70, 95, 120, 200],

    "Length_of_Stay_Days": [2, 7, 1, 3, 5,
                            4, 1, 2, 3, 6],

    "Admission_Type": [
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Planned"
    ]
}

df = pd.DataFrame(data)

df

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned


68. Using loc, display all Hyderabad patients.

In [16]:
df.loc[df["City"]=="Hyderabad"]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned

69. Using loc, display only:

Patient_ID
Age
City

for Hyderabad patients.

In [20]:
df.loc[df["City"]=="Hyderabad"][["Patient_ID","Age","City"]]

  Patient_ID  Age       City
0       P101   45  Hyderabad
2       P103   34  Hyderabad
4       P105   41  Hyderabad
6       P107   29  Hyderabad
8       P109   47  Hyderabad

70. Using loc, display Emergency patients with:

Patient_ID
Surgery_Type
Operation_Duration_Min

In [21]:
df.loc[df["Admission_Type"]=="Emergency"][["Patient_ID","Surgery_Type","Operation_Duration_Min"]]

  Patient_ID  Surgery_Type  Operation_Duration_Min
1       P102          CABG                     240
2       P103  Appendectomy                      75
5       P106          PTCA                     150
6       P107  Appendectomy                      70

71. Using loc, display patients whose:

Operation_Duration_Min > 100

and return:

Patient_ID
Surgery_Type
Operation_Duration_Min

In [22]:
df.loc[df["Operation_Duration_Min"]>100][["Patient_ID","Surgery_Type","Operation_Duration_Min"]]

  Patient_ID      Surgery_Type  Operation_Duration_Min
1       P102              CABG                     240
3       P104     Hernia Repair                     110
4       P105  Knee Replacement                     180
5       P106              PTCA                     150
8       P109     Hernia Repair                     120
9       P110  Knee Replacement                     200

72. Using iloc, display the first 5 rows.

In [23]:
df.iloc[:5]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned

73. Using iloc, display the last 4 rows.

In [24]:
df.iloc[4:]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

74. Using iloc, display rows 2 to 6.

In [26]:
df.iloc[2:6]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
5,P106,68,Nizamabad,PTCA,150,4,Emergency

75. Using iloc, display first 5 rows and first 3 columns.

In [28]:
df.iloc[:5,:3]

  Patient_ID  Age        City
0       P101   45   Hyderabad
1       P102   62    Warangal
2       P103   34   Hyderabad
3       P104   55  Vijayawada
4       P105   41   Hyderabad

76. Using iloc, display rows 1 to 7 and columns 0 to 4.

In [34]:
df.iloc[:1,:7]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned

77. Find the patient with the longest operation.

Display:

Patient_ID
Surgery_Type
Operation_Duration_Min

In [43]:
df.loc[df["Operation_Duration_Min"].idxmax(),["Patient_ID","Surgery_Type","Operation_Duration_Min"]]

Patient_ID                P102
Surgery_Type              CABG
Operation_Duration_Min     240
Name: 1, dtype: object

78. Find the patient with the shortest operation.

In [48]:
df.loc[df["Operation_Duration_Min"].idxmin(),["Patient_ID"]]

Patient_ID    P107
Name: 6, dtype: str

Find the patient with the longest hospital stay.

In [4]:
df.loc[df["Length_of_Stay_Days"].idxmax()],"Patient_ID"

(Patient_ID                     P102
 Age                              62
 City                       Warangal
 Surgery_Type                   CABG
 Operation_Duration_Min          240
 Length_of_Stay_Days               7
 Admission_Type            Emergency
 Name: 1, dtype: object,
 'Patient_ID')

Find the patient with the shortest hospital stay.

In [5]:
df.loc[df["Length_of_Stay_Days"].idxmin()],"Patient_ID"

(Patient_ID                        P103
 Age                                 34
 City                         Hyderabad
 Surgery_Type              Appendectomy
 Operation_Duration_Min              75
 Length_of_Stay_Days                  1
 Admission_Type               Emergency
 Name: 2, dtype: object,
 'Patient_ID')

81. Find the oldest patient.

In [7]:
df.loc[df["Age"].idxmax()],"Patient_ID"

(Patient_ID                            P110
 Age                                     73
 City                            Karimnagar
 Surgery_Type              Knee Replacement
 Operation_Duration_Min                 200
 Length_of_Stay_Days                      6
 Admission_Type                     Planned
 Name: 9, dtype: object,
 'Patient_ID')

82. Find the youngest patient.

In [8]:
df.loc[df["Age"].idxmin()],"Patient_ID"

(Patient_ID                        P107
 Age                                 29
 City                         Hyderabad
 Surgery_Type              Appendectomy
 Operation_Duration_Min              70
 Length_of_Stay_Days                  1
 Admission_Type               Emergency
 Name: 6, dtype: object,
 'Patient_ID')


83. Among Hyderabad patients, find the patient with the longest operation.

In [10]:
df.loc[(df["City"]=="Hyderabad")&(df["Operation_Duration_Min"].idxmax())][["Patient_ID"]]

  Patient_ID
0       P101
2       P103
4       P105
6       P107
8       P109


84. Among Emergency patients, find the patient with the longest operation.

In [11]:
df.loc[(df["Admission_Type"]=="Emergency")&(df["Operation_Duration_Min"].idxmax())][["Patient_ID"]]

  Patient_ID
1       P102
2       P103
5       P106
6       P107

85. Among Planned patients, find the patient with the longest hospital stay.

In [12]:
df.loc[(df["Admission_Type"]=="Planned")&(df["Length_of_Stay_Days"].idxmax())][["Patient_ID"]]

  Patient_ID
0       P101
3       P104
4       P105
7       P108
8       P109
9       P110

86. Among Hyderabad patients, find the youngest patient.

In [14]:
df.loc[(df["City"]=="Hyderabad")&(df["Age"].idxmin())][["Patient_ID"]]

Empty DataFrame
Columns: [Patient_ID]
Index: []

87. Among Emergency patients, find the oldest patient.

In [15]:
df.loc[(df["Admission_Type"]=="Emergency")&(df["Age"].idxmax())][["Patient_ID"]]

  Patient_ID
1       P102
2       P103
5       P106
6       P107

88. Among patients with Operation_Duration_Min > 100, find the longest hospital stay.

In [16]:
df.loc[(df["Operation_Duration_Min"]>100)&(df["Length_of_Stay_Days"].idxmax())][["Patient_ID"]]

  Patient_ID
1       P102
3       P104
4       P105
5       P106
8       P109
9       P110