In [45]:
import pandas as pd
M={"marks" : [45, 78, 65, 65, 88, 54]}
df=pd.DataFrame(M)
df

   marks
0     45
1     78
2     65
3     65
4     88
5     54

99. Find maximum without using max().

In [22]:
maximum = df["marks"].sort_values(ascending=False).iloc[0]

print("Maximum Marks:", maximum)

Maximum Marks: 92


100. Find minimum without using min().

In [26]:
minimum=df["marks"].sort_values(ascending=True).iloc[0]
print("Minimum Value:", minimum)

Minimum Value: 45


101. Count values greater than 70 without using count().

In [36]:
Count=df.loc[df["marks"]>70]
print(Count)

   marks
1     78
2     92
4     88

102. Find the second largest number without using sort().

In [41]:
second_Largest=df.nlargest(2,"marks")["marks"].iloc[1]
print("second_Largest:",second_Largest)

second_Largest: 88


103. Find the second smallest number.

In [43]:
second_smallest=df["marks"].sort_values(ascending=True).iloc[1]
print("second_smallest:",second_smallest)

second_smallest: 54


104. Find duplicate values.

In [53]:
duplicate=df[df["marks"].duplicated()]
print("duplicate value:",duplicate)

duplicate value:    marks
3     65

105. Count frequency of each value

In [54]:
df["marks"].value_counts()

marks
65    2
45    1
78    1
88    1
54    1
Name: count, dtype: int64

106. Find the first repeated value.

In [67]:
first=df["marks"].duplicated()
print(df[first].iloc[0])

marks    65
Name: 3, dtype: int64

107. Find the first non-repeated value

In [75]:
first=df["marks"].unique()
first[0]

np.int64(45)

108. Separate even and odd numbers.

In [80]:
even=df["marks"]%2==0
print(df[even])

   marks
1     78
4     88
5     54

In [81]:
odd=df["marks"]%2==1
print(df[odd])

   marks
0     45
2     65
3     65


109. Reverse the list without using reverse().

In [86]:
df[::-1]

   marks
5     54
4     88
3     65
2     65
1     78
0     45