In [2]:
import pandas as pd

data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110"],

    "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],

    "City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
             "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
             "Hyderabad", "Karimnagar"],

    "Surgery_Type": [
        "Cholecystectomy", "CABG", "Appendectomy",
        "Hernia Repair", "Knee Replacement", "PTCA",
        "Appendectomy", "Cholecystectomy",
        "Hernia Repair", "Knee Replacement"
    ],

    "Operation_Duration_Min": [90, 240, 75, 110, 180,
                               150, 70, 95, 120, 200],

    "Length_of_Stay_Days": [2, 7, 1, 3, 5,
                            4, 1, 2, 3, 6],

    "Admission_Type": [
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Planned"
    ]
}

df = pd.DataFrame(data)

df

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

━━━━━━━━━━━━━━━━━━

111. Identify and correct the error:

df[df["Admission_Type" == "Emergency"]]

In [5]:
df.loc[df["Admission_Type"]=="Emergency"]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Emergency
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Emergency
4,P105,41,Hyderabad,Knee Replacement,180,5,Emergency
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
7,P108,52,Warangal,Cholecystectomy,95,2,Emergency
8,P109,47,Hyderabad,Hernia Repair,120,3,Emergency
9,P110,73,Karimnagar,Knee Replacement,200,6,Emergency


112. Identify and correct the error:

df[df["City"] = "Hyderabad"]

In [6]:
df.loc[df["City"]=="Hyderabad"]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
4,P105,41,Hyderabad,Knee Replacement,180,5,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
8,P109,47,Hyderabad,Hernia Repair,120,3,Emergency

113. Identify and correct the error:

df[df["Age"] > 50 and df["City"] == "Hyderabad"]

In [10]:
df.loc[(df["Age"]>50)&(df["City"]=="Hyderabad")][["Patient_ID"]]

Empty DataFrame
Columns: [Patient_ID]
Index: []


114. Identify and correct the error:

df["city"]

In [11]:
df["City"]

0     Hyderabad
1      Warangal
2     Hyderabad
3    Vijayawada
4     Hyderabad
5     Nizamabad
6     Hyderabad
7      Warangal
8     Hyderabad
9    Karimnagar
Name: City, dtype: str


115. Why can this produce an error?

df.loc[df["Age"] > 50]

In [12]:
df.loc[df["Age"]>50]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
1,P102,62,Warangal,CABG,240,7,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Emergency
5,P106,68,Nizamabad,PTCA,150,4,Emergency
7,P108,52,Warangal,Cholecystectomy,95,2,Emergency
9,P110,73,Karimnagar,Knee Replacement,200,6,Emergency

116. Explain the difference between:

max()

and

idxmax()

max():- it give us Maximum  index value
df["Age"].max()
idxmax():- it gve us entire details of that Maximum value

In [17]:
df.loc[df["Age"].idxmax()],"Age"

(Patient_ID                            P110
 Age                                     73
 City                            Karimnagar
 Surgery_Type              Knee Replacement
 Operation_Duration_Min                 200
 Length_of_Stay_Days                      6
 Admission_Type                   Emergency
 Name: 9, dtype: object,
 'Age')

Explain the difference between:

loc

and

iloc

loc:- it is used if the condition is satisfied then print that value 
iloc:- it is used if the condition is satisfied then print that position of index value.